<template>
    <div class="vs-sticky-nav" :class="{ 'has-edit-button': page.isPreview() }">
        <!-- Note that the skip to component attaches to 3 hardcoded links by default, each of
         which is generated by a page component. A page with a VsMegaNav, VsPageIntro and VsFooter
          will work correctly with this component. -->
        <VsBrSkipTo />
        <header>
            <h1>Header component</h1>
        </header>

        <BrManageMenuButton :menu="menuData" />

        <!-- <ul>
            <li
                v-for="(menuItem, index) in menuItems"
                :key="index"
            >
                <a
                    :href="menuItem.getUrl()"
                >
                    {{ menuItem.model.title }}
                </a>
            </li>
        </ul> -->
    </div>
</template>

<script lang="ts" setup>
/* eslint-disable no-unused-vars */
/* eslint-disable @typescript-eslint/no-unused-vars */

import { toRefs } from 'vue';
import type { Component, Page } from '@bloomreach/spa-sdk';
import { BrManageMenuButton } from '@bloomreach/vue3-sdk';

import VsBrSkipTo from '~/components/Base/VsBrSkipTo.vue';

const props = defineProps<{ component: Component, page: Page }>();

const { component, page } = toRefs(props);

let menu = {
    $ref: '',
};
let menuData : any = {
};
let menuItems : any[] = [];

if (page.value) {
    // Menu content can be retrieved from the models on the sdk core Menu component
    // like so
    // Multiple menus may exist depending on the site

    menu = component.value.getModels().menu;
    menuData = page.value.getContent(menu.$ref);
    menuItems = menuData.items;
}
</script>
