function getDMSIconName(dmsKey: string = ''): string {
    const iconMap: Record<string, string> = {
        accesstoliet: 'fa-kit fa-vs-accessible-toilet',
        accessparkdrop: 'fa-kit fa-vs-accessible-parking',
        acco: 'fa-regular fa-bed',
        attr: 'fa-regular fa-attractions',
        audioloop: 'fa-regular fa-ear-listen',
        cafereston: 'fa-regular fa-mug-saucer',
        cate: 'fa-regular fa-utensils',
        cities: 'fa-regular fa-city',
        city: 'fa-regular fa-city',
        cycling: 'fa-regular fa-person-biking',
        dsblaccess: 'fa-regular fa-wheelchair',
        wheelchairaccess: 'fa-regular fa-wheelchair',
        even: 'fa-regular fa-calendar-range',
        familyev: 'fa-regular fa-family',
        filmev: 'fa-regular fa-camera-movie',
        hottub: 'fa-regular fa-hot-tub-person',
        parking: 'fa-regular fa-square-parking',
        petswelcom: 'fa-regular fa-dog-leashed',
        wifi: 'fa-regular fa-wifi',
        public: 'fa-kit fa-vs-public-transport',
        pubtranrte: 'fa-kit fa-vs-public-transport',
        reta: 'fa-regular fa-bag-shopping',
        spahealth: 'fa-regular fa-spa',
        vege: 'fa-kit fa-vs-vegan',
        walking: 'fa-regular fa-person-walking',
        walk: 'fa-regular fa-person-walking',
        boat: 'fa-regular fa-ferry',
        transport: 'fa-regular fa-taxi-bus',
        brekavail: 'fa-regular fa-egg-fried',
        wetroom: 'fa-kit fa-vs-accessible-shower',
        car: 'fa-regular fa-car-side',
        'map-marker': 'fa-regular fa-location-dot',
        tram: 'fa-regular fa-train-subway',
        acti: 'fa-regular fa-person-hiking',
        castle: 'fa-regular fa-chess-rook',
        history: 'fa-regular fa-landmark',
        islands: 'fa-regular fa-island-tropical',
        landscapes: 'fa-regular fa-mountain',
        landscape: 'fa-regular fa-mountain',
        sightseeing: 'fa-regular fa-binoculars',
        whisky: 'fa-regular fa-whiskey-glass-ice',
    };

    return iconMap[dmsKey] ?? `fa-regular fa-${dmsKey}`;
}

export default getDMSIconName;
