// DO NOT DELETE OR MERGE THIS BRANCH
// The purpose of this branch is to enable pure back-end branches to be tested integrated with the front end. 
//Note: You can create multiple back-end integration brances by duplicating the changes of this branch in a another branch
// git checkout -b back-end-integration-branch -b

// To force the build of a feature environment for a branch, without making the branch a PR, uncomment the line below
env.VS_BUILD_FEATURE_ENVIRONMENT = "TRUE"

env.BR_RESOURCE_API_ENDPOINT = "https://feature.visitscotland.com/resourceapi?vs_brxm_host=172.28.87.25&vs_brxm_port=8002&vs-no-redirect=true"
